title: BASS:ON
description: We are BASS:ON, where we turn bass boost up to 11 and rave into the night and dawn. We run bunker raves every now and then.
baseurl: "/bass.on"
url: "https://itisrazza.github.io"
future: true

collections:
  events:
    output: true
    sort_by: date

theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
